import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Institution } from '@/types/institution';
import { formatIndianCurrency, formatLakhs, formatDate, getNaacBadgeColor } from './utils';

const INDIGO: [number, number, number] = [99, 102, 241];
const SLATE: [number, number, number] = [15, 23, 42];
const LIGHT: [number, number, number] = [248, 250, 252];

function addSectionHeader(doc: jsPDF, title: string, y: number): number {
  doc.setFillColor(...INDIGO);
  doc.rect(14, y, 182, 8, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(title.toUpperCase(), 17, y + 5.5);
  doc.setTextColor(0, 0, 0);
  return y + 12;
}

function addField(doc: jsPDF, label: string, value: string | undefined, x: number, y: number): number {
  if (!value) return y;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...SLATE);
  doc.text(label + ':', x, y);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60, 60, 60);
  const lines = doc.splitTextToSize(value, 110);
  doc.text(lines, x + 40, y);
  return y + lines.length * 5 + 2;
}

export function generatePDF(institution: Institution): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const { profile, accreditation, management, placement, fees } = institution;

  // ── COVER PAGE ──────────────────────────────────────────────
  doc.setFillColor(...SLATE);
  doc.rect(0, 0, 210, 60, 'F');
  doc.setFillColor(...INDIGO);
  doc.rect(0, 60, 210, 3, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('INSTITUTIONAL INTELLIGENCE REPORT', 105, 25, { align: 'center' });

  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  const nameLines = doc.splitTextToSize(profile.name, 170);
  doc.text(nameLines, 105, 38, { align: 'center' });

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`${profile.type} | ${profile.city}, ${profile.state}`, 105, 52, { align: 'center' });

  doc.setTextColor(...SLATE);
  let y = 75;

  // Meta info
  const metaItems = [
    accreditation.naac ? `NAAC ${accreditation.naac.grade}` : null,
    accreditation.nirf ? `NIRF Rank #${accreditation.nirf.rank}` : null,
    profile.establishedYear ? `Est. ${profile.establishedYear}` : null,
    `Confidence: ${institution.confidenceScore}%`,
  ].filter(Boolean);

  doc.setFontSize(9);
  metaItems.forEach((item, i) => {
    doc.setFillColor(230, 232, 240);
    doc.roundedRect(14 + i * 46, y, 44, 8, 2, 2, 'F');
    doc.setTextColor(...SLATE);
    doc.text(item!, 36 + i * 46, y + 5.5, { align: 'center' });
  });
  y += 18;

  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text(`Report generated: ${new Date().toLocaleDateString('en-IN')} | Generated by EduIntel`, 105, y, { align: 'center' });
  y += 12;

  // ── SECTION 1: PROFILE ─────────────────────────────────────
  y = addSectionHeader(doc, '1. Institution Profile', y);
  y = addField(doc, 'Website', profile.website, 14, y);
  y = addField(doc, 'Address', profile.address, 14, y);
  if (profile.phone?.length) y = addField(doc, 'Phone', profile.phone.join(', '), 14, y);
  if (profile.email?.length) y = addField(doc, 'Email', profile.email.join(', '), 14, y);
  if (profile.founder) y = addField(doc, 'Founder', profile.founder, 14, y);
  if (profile.totalStudents) y = addField(doc, 'Students', profile.totalStudents.toLocaleString('en-IN'), 14, y);
  if (profile.totalFaculty) y = addField(doc, 'Faculty', profile.totalFaculty.toLocaleString('en-IN'), 14, y);
  y += 4;

  // ── SECTION 2: ACCREDITATION ────────────────────────────────
  if (y > 240) { doc.addPage(); y = 20; }
  y = addSectionHeader(doc, '2. Accreditation & Rankings', y);

  const accRows: string[][] = [];
  if (accreditation.naac)
    accRows.push(['NAAC', accreditation.naac.grade, String(accreditation.naac.cycle), String(accreditation.naac.year), accreditation.naac.cgpa ? `CGPA: ${accreditation.naac.cgpa}` : '']);
  if (accreditation.nirf)
    accRows.push(['NIRF', `Rank #${accreditation.nirf.rank}`, accreditation.nirf.category, String(accreditation.nirf.year), '']);
  if (accreditation.nba)
    accRows.push(['NBA', `${accreditation.nba.programCount} Programs`, '', accreditation.nba.year ? String(accreditation.nba.year) : '', '']);
  accreditation.otherRankings?.forEach(r =>
    accRows.push([r.body, r.rank ? `#${r.rank}` : '', r.category || '', r.year ? String(r.year) : '', r.notes || ''])
  );

  if (accRows.length) {
    autoTable(doc, {
      startY: y,
      head: [['Body', 'Grade / Rank', 'Category / Cycle', 'Year', 'Notes']],
      body: accRows,
      theme: 'striped',
      headStyles: { fillColor: INDIGO, textColor: 255, fontSize: 9 },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
  }

  // ── SECTION 3: MANAGEMENT ───────────────────────────────────
  if (y > 220) { doc.addPage(); y = 20; }
  y = addSectionHeader(doc, '3. Management & Key Contacts', y);

  if (management.length) {
    const mgmtRows = management.slice(0, 30).map(m => [
      m.name, m.designation, m.email || '—', m.phone || '—', m.confidence.toUpperCase()
    ]);
    autoTable(doc, {
      startY: y,
      head: [['Name', 'Designation', 'Email', 'Phone', 'Confidence']],
      body: mgmtRows,
      theme: 'striped',
      headStyles: { fillColor: INDIGO, textColor: 255, fontSize: 9 },
      bodyStyles: { fontSize: 7.5 },
      columnStyles: { 2: { cellWidth: 45 }, 3: { cellWidth: 30 } },
      margin: { left: 14, right: 14 },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
  }

  // ── SECTION 4: PLACEMENT ────────────────────────────────────
  if (y > 200) { doc.addPage(); y = 20; }
  y = addSectionHeader(doc, '4. Placement Ecosystem', y);

  if (placement.directorName || placement.directorEmail) {
    y = addField(doc, 'TPO Name', placement.directorName, 14, y);
    y = addField(doc, 'TPO Email', placement.directorEmail, 14, y);
    y = addField(doc, 'TPO Phone', placement.directorPhone, 14, y);
    y += 3;
  }

  const allStats = [placement.currentYear, ...(placement.historicalStats || [])].filter(Boolean);
  if (allStats.length) {
    const statsRows = allStats.map(s => [
      s.academicYear || '—',
      s.totalOffers?.toString() || '—',
      s.totalEligible?.toString() || '—',
      s.placementRate ? `${s.placementRate}%` : '—',
      s.averageCTC ? formatLakhs(s.averageCTC) : '—',
      s.highestCTC ? formatLakhs(s.highestCTC) : '—',
      s.totalCompanies?.toString() || '—',
    ]);
    autoTable(doc, {
      startY: y,
      head: [['Year', 'Offers', 'Eligible', 'Rate', 'Avg CTC', 'Highest CTC', 'Companies']],
      body: statsRows,
      theme: 'striped',
      headStyles: { fillColor: INDIGO, textColor: 255, fontSize: 9 },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
  }

  // ── SECTION 5: RECRUITERS ───────────────────────────────────
  if (placement.dreamCompanies?.length || placement.superDreamCompanies?.length) {
    if (y > 230) { doc.addPage(); y = 20; }
    y = addSectionHeader(doc, '5. Top Recruiters', y);
    if (placement.superDreamCompanies?.length) {
      y = addField(doc, 'Super Dream', placement.superDreamCompanies.join(', '), 14, y);
    }
    if (placement.dreamCompanies?.length) {
      y = addField(doc, 'Dream Companies', placement.dreamCompanies.slice(0, 20).join(', '), 14, y);
    }
    y += 4;
  }

  // ── SECTION 6: FEE STRUCTURE ────────────────────────────────
  if (fees.length) {
    if (y > 200) { doc.addPage(); y = 20; }
    y = addSectionHeader(doc, '6. Fee Structure', y);

    const feeRows = fees.map(f => [
      f.programName,
      f.degreeType,
      `${f.duration}Y`,
      f.annualFees.year1 ? formatIndianCurrency(f.annualFees.year1) : '—',
      f.annualFees.year2 ? formatIndianCurrency(f.annualFees.year2) : '—',
      f.annualFees.year3 ? formatIndianCurrency(f.annualFees.year3) : '—',
      f.annualFees.year4 ? formatIndianCurrency(f.annualFees.year4) : '—',
      f.totalFees ? formatIndianCurrency(f.totalFees) : '—',
    ]);
    autoTable(doc, {
      startY: y,
      head: [['Program', 'Degree', 'Dur', 'Year 1', 'Year 2', 'Year 3', 'Year 4', 'Total']],
      body: feeRows,
      theme: 'striped',
      headStyles: { fillColor: INDIGO, textColor: 255, fontSize: 9 },
      bodyStyles: { fontSize: 7.5 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
  }

  // ── FOOTER on all pages ─────────────────────────────────────
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150);
    doc.text(
      `${profile.name} | EduIntel Intelligence Report | Page ${i} of ${pageCount}`,
      105, 292, { align: 'center' }
    );
    doc.setDrawColor(...INDIGO);
    doc.setLineWidth(0.5);
    doc.line(14, 288, 196, 288);
  }

  doc.save(`${profile.name.replace(/\s+/g, '_')}_EduIntel_Report.pdf`);
}
