import { Institution } from '@/types/institution';
import { storage } from './storage';

const SAMPLE: Institution = {
  id: 'demo-svce-001',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  confidenceScore: 82,
  profile: {
    name: 'Sri Venkateswara College of Engineering',
    formerName: undefined,
    type: 'Engineering College',
    establishedYear: 1985,
    founder: 'Sri Venkateswara Educational Trust',
    tagline: 'Excellence in Technical Education',
    vision: 'To be a globally recognized institution producing world-class engineers with ethical values.',
    mission: 'Providing quality technical education through innovative teaching, research, and industry collaboration.',
    address: 'Post Bag 1, Pennalur Village, Sriperumbudur Taluk, Kancheepuram District',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '602117',
    phone: ['+91 44 2714 9050', '+91 44 2714 9060'],
    email: ['principal@svce.ac.in', 'info@svce.ac.in'],
    whatsapp: '+91 98400 00000',
    website: 'https://svce.ac.in',
    domain: 'svce.ac.in',
    linkedin: 'https://linkedin.com/school/svce',
    totalStudents: 5200,
    totalFaculty: 350,
    totalPrograms: 18,
    totalSchools: 12,
  },
  accreditation: {
    naac: { grade: 'A+', cycle: 3, year: 2022, cgpa: 3.34 },
    nirf: { rank: 101, category: 'Engineering', year: 2024, score: 52.4 },
    nba: {
      programCount: 8,
      programs: ['CSE', 'ECE', 'EEE', 'Mechanical', 'Civil', 'IT', 'Chemical', 'Biomedical'],
      year: 2023,
    },
    ugcCategory: 'Category II',
    ugc12B: true,
    ugc2F: true,
    aicteApproved: true,
    autonomousStatus: true,
    otherRankings: [
      { body: 'ARIIA', rank: 15, category: 'South India', year: 2023 },
      { body: 'Outlook Ranking', rank: 42, category: 'Engineering', year: 2024 },
    ],
  },
  affiliation: {
    affiliatedTo: 'Anna University',
    affiliationType: 'Autonomous',
    aicteApprovalNumber: 'AICTE/TN/2024/1234',
    aicteApprovalYear: 2024,
    ugcRecognition: true,
    ugcUnder12B: true,
    mandatoryDisclosureUrl: 'https://svce.ac.in/mandatory-disclosure',
    complianceStatus: 'Compliant',
  },
  management: [
    {
      id: 'mgmt-001',
      name: 'Dr. S. Rajendran',
      designation: 'Chairman',
      category: 'sponsoring_body',
      qualification: 'Ph.D, IIT Madras',
      email: 'chairman@svce.ac.in',
      phone: '+91 98400 11111',
      confidence: 'high',
      source: 'Official Website',
    },
    {
      id: 'mgmt-002',
      name: 'Dr. A. Krishnamurthy',
      designation: 'Principal',
      category: 'academic_leadership',
      qualification: 'Ph.D, BITS Pilani',
      email: 'principal@svce.ac.in',
      phone: '+91 44 2714 9050',
      confidence: 'high',
      source: 'Official Website',
    },
    {
      id: 'mgmt-003',
      name: 'Mr. K. Venkatesh',
      designation: 'Registrar',
      category: 'administration',
      qualification: 'MBA, Anna University',
      email: 'registrar@svce.ac.in',
      phone: '+91 44 2714 9055',
      confidence: 'high',
      source: 'Official Website',
    },
    {
      id: 'mgmt-004',
      name: 'Dr. P. Suresh',
      designation: 'Director — Placements & Training',
      category: 'placement',
      qualification: 'Ph.D, NIT Trichy',
      email: 'placement@svce.ac.in',
      phone: '+91 98411 22233',
      confidence: 'high',
      source: 'Placement Portal',
    },
    {
      id: 'mgmt-005',
      name: 'Dr. R. Meenakshi',
      designation: 'Dean — Academic Affairs',
      category: 'academic_leadership',
      qualification: 'Ph.D, Anna University',
      email: 'dean.academics@svce.ac.in',
      phone: '+91 44 2714 9061',
      confidence: 'medium',
      source: 'AI Extraction',
    },
  ],
  placement: {
    directorName: 'Dr. P. Suresh',
    directorEmail: 'placement@svce.ac.in',
    directorPhone: '+91 98411 22233',
    directorWhatsApp: '+91 98411 22233',
    currentYear: {
      academicYear: '2023-24',
      totalOffers: 2847,
      totalEligible: 3100,
      placementRate: 91.8,
      averageCTC: 650000,
      highestCTC: 4200000,
      totalCompanies: 248,
      dreamCompanyCount: 42,
      superDreamCount: 12,
    },
    historicalStats: [
      { academicYear: '2022-23', totalOffers: 2650, totalEligible: 2950, placementRate: 89.8, averageCTC: 580000, highestCTC: 3800000, totalCompanies: 220 },
      { academicYear: '2021-22', totalOffers: 2100, totalEligible: 2600, placementRate: 80.7, averageCTC: 510000, highestCTC: 3200000, totalCompanies: 185 },
      { academicYear: '2020-21', totalOffers: 1820, totalEligible: 2500, placementRate: 72.8, averageCTC: 460000, highestCTC: 2800000, totalCompanies: 162 },
    ],
    recruiters: [
      { name: 'TCS', sector: 'IT', tier: 'Regular' },
      { name: 'Infosys', sector: 'IT', tier: 'Regular' },
      { name: 'Wipro', sector: 'IT', tier: 'Regular' },
      { name: 'Cognizant', sector: 'IT', tier: 'Regular' },
      { name: 'Microsoft', sector: 'Product', tier: 'Super Dream' },
      { name: 'Google', sector: 'Product', tier: 'Super Dream' },
      { name: 'Amazon', sector: 'Product', tier: 'Super Dream' },
      { name: 'Zoho', sector: 'Product', tier: 'Dream' },
      { name: 'Freshworks', sector: 'Product', tier: 'Dream' },
      { name: 'HDFC Bank', sector: 'BFSI', tier: 'Regular' },
    ],
    dreamCompanies: ['Zoho', 'Freshworks', 'Hexaware', 'Capgemini', 'L&T Technology', 'Bosch', 'TVS Motor', 'Hyundai'],
    superDreamCompanies: ['Microsoft', 'Google', 'Amazon', 'Qualcomm', 'Texas Instruments', 'Intel', 'Apple', 'Meta'],
  },
  fees: [
    {
      id: 'fee-001',
      programName: 'B.E. Computer Science and Engineering',
      degreeType: 'B.E.',
      duration: 4,
      department: 'Department of CSE',
      annualFees: { year1: 145000, year2: 145000, year3: 145000, year4: 145000 },
      admissionFee: 25000,
      hostelFeePerYear: 72000,
      totalFees: 605000,
      feeSource: 'Official Website',
      academicYear: '2024-25',
      notes: 'Includes tuition, lab, and exam fees. Hostel is optional.',
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 'fee-002',
      programName: 'B.E. Electronics and Communication Engineering',
      degreeType: 'B.E.',
      duration: 4,
      department: 'Department of ECE',
      annualFees: { year1: 140000, year2: 140000, year3: 140000, year4: 140000 },
      admissionFee: 25000,
      hostelFeePerYear: 72000,
      totalFees: 585000,
      feeSource: 'Official Website',
      academicYear: '2024-25',
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 'fee-003',
      programName: 'M.E. Computer Science and Engineering',
      degreeType: 'M.E.',
      duration: 2,
      department: 'Department of CSE',
      annualFees: { year1: 85000, year2: 85000 },
      admissionFee: 15000,
      totalFees: 185000,
      feeSource: 'Mandatory Disclosure',
      academicYear: '2024-25',
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 'fee-004',
      programName: 'MBA',
      degreeType: 'MBA',
      duration: 2,
      department: 'School of Management',
      annualFees: { year1: 120000, year2: 120000 },
      admissionFee: 20000,
      totalFees: 260000,
      feeSource: 'Official Website',
      academicYear: '2024-25',
      lastUpdated: new Date().toISOString(),
    },
  ],
  documents: [
    { id: 'doc-001', name: 'NAAC SSR 2022', type: 'SSR', year: 2022, url: 'https://svce.ac.in/naac-ssr', status: 'Live' },
    { id: 'doc-002', name: 'AQAR 2023-24', type: 'AQAR', year: 2024, url: 'https://svce.ac.in/iqac/aqar', status: 'Live' },
    { id: 'doc-003', name: 'Mandatory Disclosure 2024', type: 'Mandatory Disclosure', year: 2024, url: 'https://svce.ac.in/mandatory-disclosure', status: 'Live' },
    { id: 'doc-004', name: 'Placement Brochure 2023-24', type: 'Placement Brochure', year: 2024, url: 'https://svce.ac.in/placements/brochure', status: 'Live' },
  ],
  sources: [
    { section: 'Institution Profile', score: 88, sourceUrl: 'https://svce.ac.in/about-us', verificationMethod: 'Web Crawl + AI Extraction', status: 'Verified' },
    { section: 'Accreditation', score: 90, sourceUrl: 'https://svce.ac.in/about-us/accreditation-and-accolades', verificationMethod: 'Web Crawl + AI Extraction', status: 'Verified' },
    { section: 'Management', score: 85, sourceUrl: 'https://svce.ac.in/about-us/administration', verificationMethod: 'Web Crawl + AI Extraction', status: 'Verified' },
    { section: 'Placement', score: 82, sourceUrl: 'https://svce.ac.in/placements', verificationMethod: 'Web Crawl + AI Extraction', status: 'Verified' },
    { section: 'Fee Structure', score: 78, sourceUrl: 'https://svce.ac.in/admissions', verificationMethod: 'Web Crawl + AI Extraction', status: 'Partial' },
  ],
};

export function seedDemoData(): void {
  if (typeof window === 'undefined') return;
  const existing = storage.getInstitutions();
  if (existing.find(i => i.id === SAMPLE.id)) return; // Already seeded
  storage.saveInstitution(SAMPLE);
}
